language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: qxlFHI90oyI9FDZUaIuGArgPHbzdmcDKx1Beh6R+vqYvKyCbSpfBq0pL8xq56AP/CGtbiWlR7v87NJ7+q7LuVQN/8Bsaz0jnxkHoWFkByXyvJTPOdLkpxlFUNSuvALL6k5yH+pZBNHgxBaEyx11cxNVVF/IzpyMwTIytyT3hb0rDbz0M45IVOfxjqkXR0zcrFLKxTYLIYT1JIKrFyBzO4WG6S/XeJmFJB3rDTfly2hpitL6hIfpEJCeT/3NPZQHzIK/M+X59H33o/TVE1RE7Vy/nC7jEOWfMexNnyZvsNJdPTl3+MMgME3L7ic7FT/mVOuQI7DhGggS3O+AvYZzY5aBHHjaofb1u3r6ZepPLBPKupXCnl97LwXyE72OJZQpXGbD2c2Iq/Z8lvv/Q0KDFbBcjELGtgcqYnxvCF/RhnMds342kQgjsJo4+ZIcAyYm0YJBEb7CczguxyIpSCCDG+zgqw55NSr/dixZuasTqIzvkQMWQR9tYVJygX6IMO5iimgMtI88JlxLdKQd8xjzkMZQwgPiWnnYEcftkwQYWATcObMUC7CfSY12TeyvNxRgl8mXECKpVJi0GUvDoIlEMpwFV5S1wR4+soS2eU+8Ke8/R1R63bMVcyylvWfB2Mrgbu6xI+Zmx/5fATqmBrxLEelwCw3eHjJukGtCcYJj3Tns=
  app: map-game-server
  on:
    repo: krothenbaum/map-game-server
